package com.liferay.krrishna.sb.remote.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MyCustomCountry service. Represents a row in the &quot;country&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.krrishna.sb.remote.model.impl.MyCustomCountryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.krrishna.sb.remote.model.impl.MyCustomCountryImpl}.
 * </p>
 *
 * @author Liferay
 * @see MyCustomCountry
 * @see com.liferay.krrishna.sb.remote.model.impl.MyCustomCountryImpl
 * @see com.liferay.krrishna.sb.remote.model.impl.MyCustomCountryModelImpl
 * @generated
 */
public interface MyCustomCountryModel extends BaseModel<MyCustomCountry> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a my custom country model instance should use the {@link MyCustomCountry} interface instead.
     */

    /**
     * Returns the primary key of this my custom country.
     *
     * @return the primary key of this my custom country
     */
    public String getPrimaryKey();

    /**
     * Sets the primary key of this my custom country.
     *
     * @param primaryKey the primary key of this my custom country
     */
    public void setPrimaryKey(String primaryKey);

    /**
     * Returns the country ID of this my custom country.
     *
     * @return the country ID of this my custom country
     */
    @AutoEscape
    public String getCountryId();

    /**
     * Sets the country ID of this my custom country.
     *
     * @param countryId the country ID of this my custom country
     */
    public void setCountryId(String countryId);

    /**
     * Returns the name of this my custom country.
     *
     * @return the name of this my custom country
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this my custom country.
     *
     * @param name the name of this my custom country
     */
    public void setName(String name);

    /**
     * Returns the a2 of this my custom country.
     *
     * @return the a2 of this my custom country
     */
    @AutoEscape
    public String getA2();

    /**
     * Sets the a2 of this my custom country.
     *
     * @param a2 the a2 of this my custom country
     */
    public void setA2(String a2);

    /**
     * Returns the a3 of this my custom country.
     *
     * @return the a3 of this my custom country
     */
    @AutoEscape
    public String getA3();

    /**
     * Sets the a3 of this my custom country.
     *
     * @param a3 the a3 of this my custom country
     */
    public void setA3(String a3);

    /**
     * Returns the number_ of this my custom country.
     *
     * @return the number_ of this my custom country
     */
    @AutoEscape
    public String getNumber_();

    /**
     * Sets the number_ of this my custom country.
     *
     * @param number_ the number_ of this my custom country
     */
    public void setNumber_(String number_);

    /**
     * Returns the idd_ of this my custom country.
     *
     * @return the idd_ of this my custom country
     */
    @AutoEscape
    public String getIdd_();

    /**
     * Sets the idd_ of this my custom country.
     *
     * @param idd_ the idd_ of this my custom country
     */
    public void setIdd_(String idd_);

    /**
     * Returns the zip required of this my custom country.
     *
     * @return the zip required of this my custom country
     */
    public int getZipRequired();

    /**
     * Sets the zip required of this my custom country.
     *
     * @param zipRequired the zip required of this my custom country
     */
    public void setZipRequired(int zipRequired);

    /**
     * Returns the active_ of this my custom country.
     *
     * @return the active_ of this my custom country
     */
    public int getActive_();

    /**
     * Sets the active_ of this my custom country.
     *
     * @param active_ the active_ of this my custom country
     */
    public void setActive_(int active_);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.liferay.krrishna.sb.remote.model.MyCustomCountry myCustomCountry);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.krrishna.sb.remote.model.MyCustomCountry> toCacheModel();

    @Override
    public com.liferay.krrishna.sb.remote.model.MyCustomCountry toEscapedModel();

    @Override
    public com.liferay.krrishna.sb.remote.model.MyCustomCountry toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
