package com.liferay.krrishna.sb.remote.model.impl;

import com.liferay.krrishna.sb.remote.model.MyCustomCountry;
import com.liferay.krrishna.sb.remote.service.MyCustomCountryLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MyCustomCountry service. Represents a row in the &quot;country&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MyCustomCountryImpl}.
 * </p>
 *
 * @author Liferay
 * @see MyCustomCountryImpl
 * @see com.liferay.krrishna.sb.remote.model.MyCustomCountry
 * @generated
 */
public abstract class MyCustomCountryBaseImpl extends MyCustomCountryModelImpl
    implements MyCustomCountry {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a my custom country model instance should use the {@link MyCustomCountry} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MyCustomCountryLocalServiceUtil.addMyCustomCountry(this);
        } else {
            MyCustomCountryLocalServiceUtil.updateMyCustomCountry(this);
        }
    }
}
